---
title: "1. Массивы"
output: word_document
---


## Задание 1

#### Вариант 1

* Создать вектор `v` из чисел `-5,-3,-1,1,3,5`.
* Вывести на экран элементы  `v` с 3-го по 5-й.
* Присвоить этим элементам значения `0,1,2` соответственно.
* Вывести на экран полученный вектор

#### Вариант 2

* Построить матрицу-строку `v`, состоящую из чисел в интервале `[10,15]`, взятых с шагом `0.1` при помощи оператора-двоеточия. 
* Определить число элементов `v`.
* Построить матрицу-строку `u`, состоящую из тех же элементов, что и `v`, при помощи функции `linspace()`.
* Продемонстрировать равенство построенных матриц.

#### Вариант 3

* Построить матрицу-столбец `p`, состоящую из чисел в интервале `[-1,4]`, взятых с шагом `0.1` при помощи оператора-двоеточия. 
* Определить число элементов `p`.
* Построить матрицу-столбец `q`, состоящую из тех же элементов, что и `p`, при помощи функции `linspace()`.
* Продемонстрировать равенство построенных матриц.


**Примечания:**

* Экран = Command Window
* Выводить нужно только то, что указано в задании. Вывод промежуточных операций подавить с помощью `;`.


## Задание 2

Графическим способом найти корень уравнения

$$
x^3-x^2-5x+6=0,
$$

расположенный на указанном промежутке числовой оси, с заданной точностью.

Подставьте найденный корень в уравнение и определите ошибку вычисления корня.

#### Вариант 1

* Область расположения корня: $[1;1.5]$.
* Точность -- не хуже 0.01.

#### Вариант 2

* Область расположения корня: $[-3;-2]$.
* Точность -- не хуже 0.02.

#### Вариант 3

* Область расположения корня: $[1.5;2.5]$.
* Точность -- не хуже 0.005.


## Задание 3

Из матриц

$$
A = \left[
\begin{array}{}
1 & 3 \\
2 & 4 \\
\end{array}
\right] , \quad
B = \left[
\begin{array}{}
5 & 7 \\
6 & 8 \\
\end{array}
\right] .
$$

как из блоков составить матрицу $C$.

#### Вариант 1

$$
C = \left[
\begin{array}{}
A & B \\
B & A \\
\end{array}
\right] .
$$

#### Вариант 2

$$
C = \left[
\begin{array}{}
A & B & B & A \\
\end{array}
\right] .
$$

#### Вариант 3

$$
C = \left[
\begin{array}{}
A \\
B \\
A \\
B \\
\end{array}
\right] .
$$


## Задание 4

Создать заданную матрицу `A`, воспользовавшись только числами, арифметическими действиями и функциями `zeros`, `ones`, `eye`.

#### Вариант 1

$$
A = \left[
\begin{array}{}
0 & 3 & 3 & 0 & 0 & 0 \\
3 & 0 & 3 & 0 & 0 & 0 \\
3 & 3 & 0 & 0 & 0 & 0 \\
8 & 0 & 0 & 2 & 4 & 4 \\
0 & 8 & 0 & 4 & 2 & 4 \\
0 & 0 & 8 & 4 & 4 & 2 \\
\end{array}
\right] .
$$

#### Вариант 2

$$
A = \left[
\begin{array}{}
3 & 1 & 1 & 1 & 1 & 0 \\
1 & 3 & 1 & 1 & 1 & 0 \\
1 & 1 & 3 & 1 & 1 & 0 \\
-3 & -5 & -5 & 0 & 2 & 2 \\
-5 & -3 & -5 & 2 & 0 & 2 \\
-5 & -5 & -3 & 2 & 2 & 0 \\
\end{array}
\right] .
$$

#### Вариант 3

$$
A = \left[
\begin{array}{}
1 & 0 & 0 & 3 & 0 & 0 \\
1 & 0 & 0 & 0 & 3 & 0 \\
1 & 0 & 0 & 0 & 0 & 3 \\
0 & 5 & 5 & -2 & 2 & 2 \\
5 & 0 & 5 & 2 & -2 & 2 \\
5 & 5 & 0 & 2 & 2 & -2 \\
\end{array}
\right] .
$$


## Задание 5

* Найти решение системы уравнений $AX = b$. 
* Определите погрешность вычисления корней по формуле: $\mathrm{err} = |AX-b|$.

#### Вариант 1

$$
\begin{array}{lll}
x + 3y - 2z &=& 5, \\
3x + 5y + 6z &=& 7, \\
2x + 4y + 3z &=& 8 .
\end{array}
$$

#### Вариант 2

$$
\begin{array}{lll}
x_1 - x_2 + x_3 &=& 0, \\
10x_2 + 25x_3 &=& 90, \\
20x_1 + 10x_2 &=& 80
\end{array}
$$

#### Вариант 3

$$
\begin{array}{lll}
3x + y + z &=& -2, \\
5x - y - z &=& 10, \\
x - y + 5z &=& -12 .
\end{array}
$$


## Задание 6

#### Вариант 1

Ввести строки `s1` (ваше имя, латинскими буквами) и `s2` (ваша фамилия, латинскими буквами). При необходимости дополнить строки пробелами так, чтобы длины s1 и s2 совпадали. Длину строки можно узнать в окне **Workspace** или с помощью функции `length`.

Выполнить над `s1` и `s2` следующие действия:

1. `si = [s1 s2]`
2.`sii = [s1; s2]`
3. `siii = si’`
4. `siv = si(end:-1:1)`

#### Вариант 2

Пусть `x` — одномерный массив. Верно ли записано на языке MATLAB математическое выражение? Если нет, исправьте ошибку. Для каждой строки таблицы решение должно содержать ответ "да"/"нет" и синтаксически правильную запись выражения.

№ | Математическое выражение | Запись на MATLAB
--|--------------------------|--------------------
1 | $x^3\cos2x^2+x$          | `x.^3*cos(2*x)^2+x`
2 | $\frac{1+x^2+2x}{x\cos x^2}$ | `(1+x.^2+2*x)/(x.*cos(x.^2))`
3 | $2x^2 e^{x^2}$           | `2*x.^2.*exp(x^2)`
4 | $-x + \frac{x^3}{3x}$    | `-x + x.^3/3*x`
5 | $\frac{1+3x\sin x}{x^2}$ | `(1+3*x.*sin(x)./x.^2`

#### Вариант 3

Создать матрицу-столбец `B` из 10 элементов -- случайных чисел, равномерно распределенных на интервале `[1,5]`.

**Примечание:** Случайные числа создаются функцией `rand`.


## Задание 7

Задан массив

$$
A = \left[
\begin{array}{}
1 & 0 & 0 & 3 & 0 & 0 \\
1 & 0 & 0 & 0 & 3 & 0 \\
1 & 0 & 0 & 0 & 0 & 3 \\
0 & 5 & 5 & -2 & 2 & 2 \\
5 & 0 & 5 & 2 & -2 & 2 \\
5 & 5 & 0 & 2 & 2 & -2 \\
\end{array}
\right] .
$$

С помощью логической индексации найти:

#### Вариант 1

Количество неотрицательных элементов $A$.

#### Вариант 2

Сумму отрицательных элементов $A$.

#### Вариант 3

Количество элементов $A$, равных нулю.

