---
title: "2. Двумерная графика"
output: word_document
---


## Задание 1

Построить график функции

$$
y = \frac{\sin^2 x}{x}
$$
на промежутке [0.01;4$\pi$] с шагом 0.001 заданным стилем. $\pi$ задается как `pi`.

#### Вариант 1

Цвет линии — красный, стиль — штрих-пунктир. Начертить на графике сетку.

#### Вариант 2

Цвет линии — фиолетовый, стиль — пунктир, маркер — кружок. Начертить на графике сетку.

#### Вариант 3

Цвет линии — зеленый, стиль — сплошная, маркер — звездочка. Начертить на графике сетку.


## Задание 2

#### Вариант 1

* Построить график функции $y = \frac{x^3 - 0.3x}{1+2x}$ на интервале $[0,3]$ с шагом 0.01. Линия отсутствует, маркер — точка. Начертить на графике сетку.
* Что произойдет, если попытаться построить график этой же функции на интервале $[-2,3]$. Отчего так происходит?

#### Вариант 2

При движении тела, брошенного под углом к горизонту, координаты тела изменяются по закону

$$
\begin{array}{lll}
  x &=& x_0 + v_0 t \cos\alpha, \\
  y &=& y_0 + v_0 t \sin\alpha - \frac{g t^2}{2}, 
\end{array}
$$

* $(x_0,y_0)$ — координаты точки старта — (0,0);
* $v_0$ — начальная скорость движения тела — 100 м/с;
* $\alpha$ — угол бросания — 35 градусов к горизонту;
* $g = 9.8$ м/с$^2$ — ускорение силы тяжести;
* $t$ — время.

Построить график движения тела для первых 10 секунд его полета. Шаг по времени -- 0.01 с. Начертить на графике сетку.

Определить высоту полета тела при t = 10 c.

#### Вариант 3

Построить график полета тела, как в варианте 2. Определить максимальную высоту полета тела. 


## Задание 3

Постройте графики функций при заданных условиях. На графиках начертите сетку.

#### Вариант 1

Постройте графики функций

$$
f(x) = \frac{\sin x}{x+1}, \quad g(x) = e^{-x}\cos(x)
$$
на промежутке $[0; 2\pi]$ с шагом 0.01 в разных графических окнах (figure). 

Кривая на первом графике должна быть красного цвета, на втором — зеленого с маркером-кружком.

#### Вариант 2

Постройте графики функций

$$
f(x) = \sin^2 x - \cos x^2, \quad g(x) = x^2\sin3x
$$
на промежутке $[1; 2\pi]$ с шагом 0.01 в общих осях координат. 

График `f(x)` — сплошная линия зеленого цвета, маркер — звездочка, `g(x)` — пунктирная линия красного цвета. 

#### Вариант 3

Постройте графики функций

$$
f(x) = \frac{\sin x}{x+1}, \quad g(x) = e^{-x}\cos(x)
$$
на промежутке $[0; 2\pi]$ с шагом 0.005 в общем графическом окне на разных координатных осях. 

Кривая на первом графике должна быть зеленого цвета, на втором — желтого.


## Задание 4

Построить график кусочно-непрерывной функции

#### Вариант 1

$$
y = \left\{
\begin{array}{ll}
\pi - \sin x, & -2\pi \le x \le -\pi , \\
\pi - |x|, & -\pi < x \le \pi , \\
\pi - \sin^3 x, & \pi < x \le 2\pi .
\end{array}
\right.
$$

#### Вариант 2

$$
y = \left\{
\begin{array}{ll}
2.5x - 1, & x < 1 , \\
-2.5x + 4, & 1 \le x \le 3 , \\
1.5x - 8, & x > 3 .
\end{array}
\right.
$$


#### Вариант 3

$$
y = \left\{
\begin{array}{ll}
-3, & x < -1 , \\
2x - 1, & -1 \le x < 2 , \\
3, & x \ge 2 .
\end{array}
\right.
$$


## Задание 5

Постройте график функции, координаты `x` и `y` которой заданы уравнениями $x=x(t)$, $y=y(t)$ (параметр `t` имеет смысл угла) в виде многоугольника, заполненного заданным цветом. Отрезки координатных осей сделать равными (`axis square`). Шаг изменения `t` задать не хуже `pi/100`.

**Примечание:** построение плоской фигуры с заполнением цветом осуществляется функциями `fill` или `patch`.

#### Вариант 1

$$
\begin{array}{lll}
x & = & (1+\sin(t))\cdot(1+0.9\cos(8t))\cdot(1+0.1\cos(24t))\cdot(0.5+0.05\cos(140t))\cdot\cos(t), \\
y & = & (1+\sin(t))\cdot(1+0.9\cos(8t))\cdot(1+0.1\cos(24t))\cdot(0.5+0.05\cos(140t))\cdot\sin(t).
\end{array}
$$

Параметр $t$ изменяется в интервале $[-pi;\pi]$.

Внутренность многоугольника закрасить зеленым цветом.

#### Вариант 2

Координаты:

$$
\begin{array}{lll}
x & = & (1-\sin(t))\cdot\cos(t)^3, \\
y & = &(1/3)\cdot(1-\sin(t))\cdot\sin(t)-(1/3)\cdot\sin(t)^2,
\end{array}
$$

Параметр $t$ изменяется в интервале $[0;2\pi]$.

Внутренность многоугольника закрасить красным цветом.

#### Вариант 3

Координаты:

$$
\begin{array}{lll}
x &=& (1+\sin(t))\cdot(1-0.9|\sin(4t)|)\cdot(0.9+0.05\cos(200t))\cdot\cos(t), \\
y &=& (1+\sin(t))\cdot(1-0.9|\sin(4t)|)\cdot(0.9+0.05\cos(200t))\cdot\sin(t).
\end{array}
$$

$t$ изменяется в интервале $[-\pi;\pi]$.

Внутренность многоугольника закрасить зеленым цветом.

