---
title: "3. Управление вычислительным процессом"
output: html_document
---


## Задание 1

#### Вариант 1

В США оценки ставятся в баллах: от 0 до 4 (4 ставится отличникам, а 0 — двоечникам). Числовым баллам соответствуют буквенные оценки:

Баллы	              | Оценки
--------------------|--------
от >= 3.5 до 4	    | A
от >= 2.5 до < 3.5	| B
от >= 1.5 до < 2.5	| C
от >= 0.5 до < 1.5	| D
< 0.5 	            | F

Составьте программу, которая по заданному числу баллов выводит на экран соответствующую им буквенную оценку. Ввод данных пользователем организуйте с помощью функции `input`, проверку — оператором `if`, а вывод оценки — при помощи `disp`.

#### Вариант 2

Пусть `a` — целое число. При помощи условного оператора организовать проверку условия: если `a` равно 10, 20 или 30, то вывести текущее значение `a`; в остальных случаях вывести текст 'None of the values are matching'.

#### Вариант 3

Пусть `t` — случайное число в диапазоне от 0 до 1. Вывести на экран значение `s`, равное

$$
s = \left\{
\begin{array}{ll}
0, & t > 0.75 , \\
1, & t < 0.25 , \\
1-2(t-0.25), & 0.25 \le t \le 0.75 .
\end{array}
\right.
$$


## Задание 2

#### Вариант 1

Для заданного числа $x$ вычислите первое из чисел последовательности $\sin x$, $\sin \sin x$, $\sin \sin \sin x$, ..., меньшее по модулю 0.01. На каком месте в последовательности находится это число? ($\sin x$ — 1, $\sin \sin x$ — 2, ...).

#### Вариант 2

Составьте программу для вычисления суммы ряда: 

$$
1 - 1/2 + 1/3 - 1/4 + .... + 1/9999 - 1/10000.
$$

#### Вариант 3

Вычислить и вывести в командное окно сумму $1 – A + A^2 – A^3 + ... + (–1)^N A^N$ при A = 5 и N = 20. 


## Задание 3

#### Вариант 1

Вычислить сумму

$$
s = \sum_{i=1}^{20} \sum_{j=1}^{20} \frac{(-1)^{i+j}}{(2i+j)^2} .
$$

#### Вариант 2

Начальный вклад клиента в банк составляет 100000 грн. Процент годового дохода: 12%. К основной сумме процент не добавляется. Определите, через сколько лет сумма на счете клиента вдвое превысит начальный вклад.

#### Вариант 3

Начальный вклад клиента в банк составляет 100000 грн. Процент годового дохода: 12%. Ежегодно, процент добавляется к основной сумме вклада. Определите, через сколько лет сумма на счете клиента вдвое превысит начальный вклад.


## Задание 4

#### Вариант 1

Дано число произвольное четырехзначное число $N$. Составить программу, вычисляющую сумму цифр этого числа.

#### Вариант 2

Торговая фирма в первый день работы реализовала товаров на 35000 грн, а затем ежедневно увеличивала выручку на 3%. Сколько дней придется торговать фирме, чтобы сумма ежедневной выручки достигла 120000 грн?

#### Вариант 3

Для заданного числа $x$ вычислите первое из чисел последовательности $\cos x$, $\cos \cos x$, $\cos \cos \cos x$, ..., меньшее по модулю 0,01. В случае, если это условие не выполняется для 100 первых членов последовательности, выведите сообщение об ошибке.


## Задание 5

#### Вариант 1

Сгенерировать случайное трехзначное число, оканчивающееся на ноль.

#### Вариант 2

Вывести все квадраты натуральных чисел, не превосходящих заданного числа $N$.

#### Вариант 3

Вычислить факториал целого числа $N$: $N<10$ (без использования встроенной функции).

$0! = 1$, $1! = 1$, $2! = 1 \cdot 2$, $3! = 1 \cdot 2 \cdot 3$, ...

