---
title: "4. Функции. Ввод/вывод"
output: word_document
---


## Задание 1

#### Вариант 1

Создать функцию
$$
y = \left\{
\begin{array}{ll}
+1, & \text{если } x \ge 0, \\
-1, & \text{если } x < 0,
\end{array}
\right.
$$
принимающую на вход вектор `x`, и продемонстрировать ее работоспособность на примере вектора
```
x = [1 -3 0 4 3 -5 -7];
```

#### Вариант 2

Создать функцию `squares`, реализующую сумму квадратов двух чисел. Создать основной файл для вызова функции и продемонстрировать ее работоспособность.

#### Вариант 3

Создать функцию, реализующую вычисление $n$ первых чисел Фибоначчи. Числа Фибоначчи вычисляются по формуле

$$
F_1=1, \quad F_2=1, \quad F_n=F_{n-1}+F_{n-2}.
$$


## Задание 2

#### Вариант 1

Создать функцию, которая для заданного одномерному массиву определяет номер элемента с наибольшим отклонением от среднего арифметического элементов массива.

#### Вариант 2

Создать функцию
$$
y = \left\{
\begin{array}{ll}
+1, & \text{если } x > 0, \\
-1, & \text{если } x < 0,\\
0, & \text{если } x = 0, 
\end{array}
\right.
$$
принимающую на вход вектор `x`, и продемонстрировать ее работоспособность.

#### Вариант 3

Создать функцию
$$
y = \left\{
\begin{array}{ll}
x^2, & \text{если } -2 \le x < 2, \\
x^2+4x+5, & \text{если } x \ge 2,\\
4, & \text{если } x < -2, 
\end{array}
\right.
$$
принимающую на вход вектор `x`, и продемонстрировать ее работоспособность.


## Задание 3

Найти **все** действительные корни уравнения при помощи `fzero()`. Подтвердить результат при помощи `roots()`. Отобразить найденные корни на комплексной плоскости.

#### Вариант 1

$$
x^3 - 5x^2 - x + 2 = 0 .
$$

#### Вариант 2

$$
x^5 + x + 1 = 0 .
$$

#### Вариант 3

$$
x^4 + 2x^3 - 4x^2 + 7 = 0 .
$$


## Задание 4

#### Вариант 1

В файле `Altitude.txt` записана траектория полета ракеты: в первом столбце — время в секундах, во втором — высота полета в метрах.

Составьте программу, считывающую данные из этого файла и строящую график зависимости высоты полета ракеты от времени.

#### Вариант 2

Составьте программу, которая:

* создает матрицу `A` размера 5х3, состоящую из случайных чисел, равномерно распределенных в интервале $[0;10]$;
* сохраняет ее в текстовом файле `data.txt` с разделителем `','`;
* загружает эту матрицу в Workspace с помощью `csvread()`.

#### Вариант 3

Составьте программу, которая:

* Считывает данные из таблицы `ExpData.xls`.
* Считывает данные из ячеек `B2:C4` листа `Лист2` той же таблицы.

Продемонстрируйте работоспособность программы.


## Задание 5

Запишите массив `A` в текстовый файл при помощи `fprintf`. Добавьте указанный заголовок.

#### Вариант 1

```
x = 0:.1:2*pi;
A = [x; sin(x)];
```

Заголовок: `x sin(x)`

#### Вариант 2

```
x = -pi:.1:pi;
A = [x; cos(x)];
```

Заголовок: `x cos(x)`

#### Вариант 3

```
x = 0:.1:4;
A = [x; x.^2];
```

Заголовок: `x x^2`

