---
title: "5. Трехмерная графика"
output: html_document
---


## Задание 1

Построить графики пространственных кривых. Тип маркера -- "точка", цвет и стиль линии выбрать самостоятельно.

#### Вариант 1

$$
\begin{array}{lll}
x &=& \frac{a\cos t}{t}, \\
y &=& \frac{a\sin t}{t}, \\
z &=& at, \\
\end{array}
$$
где $a=2$, $\pi \le t \le 10\pi$.

#### Вариант 2

$$
\begin{array}{lll}
x &=& 10\cos t - 5\cos 2t, \\
y &=& 10\sin t - 5\sin 2t, \\
z &=& 10t ,
\end{array}
$$
$0 \le t \le 10\pi$.

#### Вариант 3

$$
\begin{array}{lll}
x &=& 2\cos t \cdot (1 + \cos t), \\
y &=& 2\sin t \cdot (1 + \cos t), \\
z &=& 2t ,
\end{array}
$$
$0 \le t \le 10\pi$.


## Задание 2

Загрузить координаты точек из файла. Отобразить точки при помощи `plot3` или `scatter3`.

#### Вариант 1

Файл: `cdata1.csv`.

#### Вариант 2

Файл: `cdata2.csv`.

#### Вариант 3

Файл: `cdata3.csv`.


## Задание 3

Построить график поверхности $z = f(x,y)$ в заданной области с помощью графических функций: 

* mesh
* surf

Шаг сетки выбрать по своему усмотрению. Сделать подписи к осям координат и заголовок графика. В заголовке указать отображаемую на графике функцию.

#### Вариант 1

$$
z = x\exp(-x^2 - y^2) .
$$
Область определения: $-3\le x,y \le 3$.

#### Вариант 2

$$
z = \sin 2x \cos y .
$$
Область определения: $0\le x,y \le 2\pi$.

#### Вариант 3

$$
z = \frac{x}{x^2 + y}.
$$
Область определения: $0\le x \le 5$, $1 \le y \le 3$.


## Задание 4

Построить график поверхности $z = f(x,y)$ в заданной области с помощью графических функций: 

* contour
* meshc

Шаг сетки выбрать по своему усмотрению. Сделать подписи к осям координат и заголовок графика. В заголовке указать отображаемую на графике функцию.

#### Вариант 1

$$
z = -(1-\cos 4\pi y)^{1/4}\cdot (1-\cos 2\pi x)^{1/4} .
$$

Область определения: $0\le x \le 3$, $0 \le y \le 1$.

#### Вариант 2

$$
z = \exp\left(-\sqrt{x^2+y^2} \right) \cdot \cos 4x \cdot \cos 4y;
$$
Область определения: $-1\le x \le 1$, $-1 \le y \le 1$.

#### Вариант 3

$$
\begin{array}{lll}
x &=& r \cos \theta, \\
y &=& r \sin \theta, \\
z &=& \exp(-r) \cos 4x \cos 4y.
\end{array}
$$
Область определения: $0 \le r \le 1.7$, $0 \le \theta \le 2\pi$.


## Задание 5

Постройте множество Жюлиа (`julia.m`), самостоятельно выбрав начальную точку. Отобразите выбранную начальную точку в заголовке графика и сделайте скриншот полученного множества.

Постройте множество Жюлиа, применив для итераций следующие функции:

#### Вариант 1

* `Z.^3 + C`
* `sin(Z).*cos(Z)`

#### Вариант 2

* `Z.^4 + C`
* `cosh(Z)`

#### Вариант 3

* `sinh(Z)`
* `cot(Z)`


## Задание 6

Запрограммируйте для одномерного клеточного автомата (`onedimca.m`) следующие правила: 

#### Вариант 1

111	| 110	| 101	| 100	| 011	| 010	| 001	| 000 |
----|-----|-----|-----|-----|-----|-----|-----|
 1	| 0	  | 0	  | 1	  | 1	  | 0	  | 1	  | 0   |

#### Вариант 2

111	| 110	| 101	| 100	| 011	| 010	| 001	| 000 |
----|-----|-----|-----|-----|-----|-----|-----|
 0	| 0	  | 1	  | 0	  | 1	  | 1	  | 1	  | 0   |

#### Вариант 3

111	| 110	| 101	| 100	| 011	| 010	| 001	| 000 |
----|-----|-----|-----|-----|-----|-----|-----|
 0	| 1	  | 0	  | 1	  | 1	  | 1	  | 0	  | 0   |

Проследите за эволюцией данного автомата. В конце сделайте скриншот и поместите его в отчет.


## Задание 7

Для всех вариантов.

Получите на экране картину движения точек, моделирующих случайные блуждания на плоскости. На каждом шаге координаты частицы $x$ и $y$ случайным образом принимают значения +1, 0 или -1. Число шагов -- не менее 300. 

Выведите номер шага в заголовок графика. Для итоговой картинки сделайте скриншот и поместите его в отчет.
