---
title: "6. Символьные расчеты. Математический анализ"
output: word_document
---


## Задание 1

Найти корни уравнения $f(x) = 0$ с помощью функции `solve`.

Построить график кривой, заданной уравнением. На графике построить сетку и отметить действительные корни уравнения (если они существуют) точками с маркером-кружком красного цвета.

#### Вариант 1

$$
x^5 - x - 2 = 0 .
$$

#### Вариант 2

$$
x^4 + 2x^3 - 4x^2 + 7 = 0 .
$$

#### Вариант 3

$$
x^3 - 2x^2 + x + 5 = 0 .
$$


## Задание 2

Решить систему линейных уравнений

1. при помощи `solve()`;
2. используя матричную запись системы $Ax=b$.

Сравните полученные решения, преобразовав символьные значения в вещественные числа (функцией `eval`) и вычислив модуль разности между решениями. Что можно сказать о различии между решениями?

#### Вариант 1

$$
\begin{array}{lll}
3x_1 + 5x_2 - x_3 &=& 8, \\
2x_1 - 2x_2 + 4x_3 &=& 3, \\
4x_1 + 7x_2 + 3x_3 &=& 5. \\
\end{array}
$$

#### Вариант 2

$$
\begin{array}{lll}
2x_1 + 3x_2 + x_3 &=& 2, \\
3x_1 + 1x_2 + 2x_3 &=& 7, \\
x_1 + 2x_2 + 3x_3 &=& 3. \\
\end{array}
$$

#### Вариант 3

$$
\begin{array}{lll}
9x_1 - 10x_2 - x_3 &=& 4, \\
3x_1 - 7x_2 + 8x_3 &=& -3, \\
7x_1 + 6x_2 + 5x_3 &=& -7. \\
\end{array}
$$


## Задание 3

Вычислить предел

#### Вариант 1

$$
\lim_{x\rightarrow \infty}\frac{2x^3+x^2+5}{3x^3+x-1} .
$$

#### Вариант 2

$$
\lim_{x\rightarrow 4}\frac{x^2-6x+8}{x^2-5x+4} .
$$

#### Вариант 3

$$
\lim_{x\rightarrow \infty}\frac{7x^4+2x^3-14}{5x^4+x^3+x^2+x-1} .
$$


## Задание 4

Вычислить первую и вторую производные функции

#### Вариант 1

$$
y = \sqrt{10-x^2} .
$$

#### Вариант 2

$$
y = a\sqrt{x} + x \sqrt{a}.
$$

#### Вариант 3

$$
y = \frac{1}{3}x^3 - \frac{3}{2}x^4 + \frac{13}{5}x^5 .
$$


## Задание 5

Вычислить интегралы

#### Вариант 1

$$
\int \frac{x^2}{7+3x^3} dx ,
$$
$$
\int_{0}^\pi \sin x dx .
$$

#### Вариант 2

$$
\int \cos 3x dx ,
$$
$$
\int_{-a}^a x^2 dx .
$$

#### Вариант 3

$$
\int \sin (x^2) x dx ,
$$
$$
\int_{-1}^1 \frac{dx}{1+x^2} .
$$


## Задание 5

Разложить функцию в ряд Тейлора

#### Вариант 1

$$
y = \sin x
$$
в окрестности точки $x=0$ с точностью до членов 6-го порядка.

#### Вариант 2

$$
y = \cos x
$$
в окрестности точки $x=0$ с точностью до членов 6-го порядка.

#### Вариант 3

$$
y = \sqrt{10-x^2}
$$
в окрестности точки $x=0$ с точностью до членов 5-го порядка.

Постройте графики исходной функции и ее разложения в ряд Тейлора на интервале $x\in[-1;1]$. На графике построить сетку. Для преобразования символьного выражения в вещественные числа использовать `eval()`.


## Задание 6

Вычислить сумму ряда

#### Вариант 1

$$
\sum_{n=1}^\infty \frac{6}{9n^2+12n-5} .
$$

#### Вариант 2

$$
\sum_{n=1}^\infty \frac{1}{n(n+1)} .
$$

#### Вариант 3

$$
\sum_{n=1}^\infty \frac{4n-3}{n^2+1} .
$$

Построить график частичных сумм ряда для $n \in [1,100]$. Для этого удобно воспользоваться функцией `cumsum`.
